############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
weight = 2
name = "About"
hasChildren = true

    [[main]]
    parent = "About"
    name = "FAQs"
    url = "about/"
    weight = 2

    [[main]]
    parent = "About"
    name = "Staff"
    url = "staff/"
    weight = 1

    [[main]]
    parent = "About"
    name = "History"
    url = "history/"
    weight = 1

[[main]]
weight = 3
name = "News"
hasChildren = true

    [[main]]
    parent = "News"
    name = "Calendar"
    url = "https://uccdga.churchcenter.com/calendar"
    weight = 1

[[main]]
name = "Worship"
url = "worship/"
weight = 6

[[main]]
weight = 7
name = "Grow"
hasChildren = true

    [[main]]
    parent = "Grow"
    name = "Children"
    url = "children/"
    weight = 1

    [[main]]
    parent = "Grow"
    name = "Youth"
    url = "/youth"
    weight = 2

    [[main]]
    parent = "Grow"
    name = "Adult"
    url = "adult/"
    weight = 3  

[[main]]
name = "Reach"
url = "reach/"
weight = 8

[[main]]
name = "Care"
url = "care/"
weight = 9

  
[[main]]
name = "Contact"
url = "contact/"
weight = 10


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Staff"
url = "staff/"
weight = 3

[[footer]]
name = "Worship"
url = "worship/"
weight = 4

[[footer]]
name = "Family Ministries"
url = "family/"
weight = 5

[[footer]]
name = "Contact"
url = "contact/"
weight = 7