############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Staff"
url = "staff/"
weight = 3

[[main]]
name = "Calendar"
url = "https://uccdga.churchcenter.com/calendar"
weight = 5

[[main]]
weight = 6
name = "More"
hasChildren = true

  [[main]]
  parent = "More"
  name = "Worship"
  url = "worship/"
  weight = 1

  [[main]]
  parent = "More"
  name = "Family Ministries"
  url = "family/"
  weight = 2
  
[[main]]
name = "Contact"
url = "contact/"
weight = 7


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Staff"
url = "staff/"
weight = 3

[[footer]]
name = "Worship"
url = "worship/"
weight = 4

[[footer]]
name = "Family Ministries"
url = "family/"
weight = 5

[[footer]]
name = "Contact"
url = "contact/"
weight = 7