############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Leaders"
url = "leader/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "Calendar"
url = "https://uccdga.churchcenter.com/calendar"
weight = 5

[[main]]
weight = 6
name = "More"
hasChildren = true

  [[main]]
  parent = "More"
  name = "Family Ministries"
  url = "family/"
  weight = 1

  [[main]]
  parent = "More"
  name = "FAQ"
  url = "faq/"
  weight = 3
  
[[main]]
name = "Contact"
url = "contact/"
weight = 7


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Leaders"
url = "leader/"
weight = 3

[[footer]]
name = "Blog"
url = "blog/"
weight = 4

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contact"
url = "contact/"
weight = 7